version: "3.9"
services:
  app:
    container_name: fesvd_containder
    restart: always
    build:
      context: ./
      target: dev
      dockerfile: Dockerfile
    volumes:
        - .:/app
        - /app/node_modules
        - /app/.next
    ports:
      - "3000:3000"