import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import LeftSidebar from "@/components/shared/Leftsidebar";
import Bottombar from "@/components/shared/Bottombar";
import Topbar from "@/components/shared/Topbar";
import Provider from "@/components/shared/Provider";
import { getServerSession } from "next-auth";
import { authOptions } from "@/src/lib/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Service Desk System",
  description: "Generated by Y.Thutchakorn",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <Provider>
        <body className={inter.className}>
          {session && <Topbar />}
          <main className="flex flex-row">
            {session && <LeftSidebar />}
            {session ? (
              <section className="main-container">
                <div className={`w-full ${session ? "max-w-screen-2xl" : ""}`}>
                  {children}
                </div>
              </section>
            ) : (
              <div className={`w-full ${session ? "max-w-screen-2xl" : ""}`}>
                {children}
              </div>
            )}
          </main>
          {session ? <Bottombar /> : null}
        </body>
      </Provider>
    </html>
  );
}

/*
<html lang="en">
      <body>
        <Providers>
          <main className="flex flex-row">
            <div className="w-full max-w-screen-2xl">{children}</div>
          </main>
        </Providers>
      </body>
    </html>
    
    <html lang="en">
      <Providers>
      <body className={inter.className}>
      <Topbar/>
        <main className='flex flex-row'>
          <LeftSidebar/>
          <section className='main-container'>
            <div className='w-full max-w-screen-2xl'>{children}</div>
          </section>
        </main>
        <Bottombar/>
      </body>
      </Providers>
    </html>


    */
