import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import LeftSidebar from '@/components/shared/Leftsidebar'
import Bottombar from '@/components/shared/Bottombar'
import Topbar from '@/components/shared/Topbar'
import Provider from '@/components/shared/Provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Service Desk System',
  description: 'Generated by Y.Thutchakorn',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <Provider>
      <body className={inter.className}>
      <Topbar/>
        <main className='flex flex-row'>
          <LeftSidebar/>
          <section className='main-container'>
            <div className='w-full max-w-screen-2xl'>{children}</div>
          </section>
        </main>
        <Bottombar/>
      </body>
      </Provider>
    </html>
  )
}
